export const data = [
  {
    id: "1",
    name: "AirGarage",
    img_url:
      "https://photos.angel.co/startups/i/4462956-636feb35abe46aa64c5af32d29eb9e3e-medium_jpg.jpg?buster=1501776720",
    info: "AirGarage is working to repurpose the 30% of the American city currently occupied by parking. As a full-stack parking operator, we automate the operation of parking lots and enable churches and businesses to rent out parking to drivers on demand. Our mission is to restore vibrancy in cities and transform these single-use spaces into multi-use hubs to support a future filled with cloud kitchens, micro-mobility, autonomous vehicles, on-demand fulfillment, and more.",
    status: "Researching",
    contact: "airgarage@email.com",
    location: ["San Francisco"],
    revenue: "1.6M",
    funding: "2M",
    size: "11-50",
  },
  {
    id: "2",
    name: "Airtable",
    img_url:
      "https://photos.angel.co/startups/i/623000-9d210a39051abc7accec1dc686888dcc-medium_jpg.jpg?buster=1589312000",
    info: "Airtable's mission is to democratize software creation. We believe that software stands to be the single most impactful way anyone can bring their ideas to life, yet that few people can actually access it as a creative medium. Airtable enables everyone to experience the power of creating, not just using, software. Headquartered in San Francisco, Airtable has raised $170M in venture funding to date, most recently a $100M Series C from Benchmark, Thrive, and Coatue.",
    status: "Approved",
    contact: "airtable@email.com",
    location: ["Austin", "New York", "San Francisco"],
    revenue: "115M",
    funding: "170.6M",
    size: "201-500",
  },
  {
    id: "3",
    name: "Bloomscape",
    img_url:
      "https://photos.angel.co/startups/i/6060025-c5c632d78c5fd53ab74781b1a7d908bb-medium_jpg.jpg?buster=1589599392",
    info: "Plants are amazing! They make life better, but buying them is a pain. Imagine stuffing a 6' plant in the trunk of your car. Bloomscape's mission is to make buying plants a whole lot more enjoyable. Our site makes selecting the right plants easy and we’ve developed a proprietary way of shipping fully-grown, already potted plants through Fedex right to your door, for the same prices you pay at an urban garden center. No one else can do this.",
    status: "Declined",
    contact: "bloomscape@email.com",
    location: ["Detroit"],
    revenue: "17.6M",
    size: "11-50",
  },
  {
    id: "4",
    name: "Calm",
    img_url:
      "https://photos.angel.co/startups/i/89425-f7e607ef282332eb355deaac362e78fc-medium_jpg.jpg?buster=1589609526",
    info: "Calm is best known as a meditation, sleep and mental wellness app, available in both the App Store and Google Play store. It is the #1 app for meditation and sleep, with over 36 million downloads to date. It was named by Apple as the 2017 iPhone App of the Year; by Google Play as an “Editors’ Choice” in 2018; and found by a major study of 200,000 iPhone users to be “the world’s happiest app” – the single app that left users feeling happiest from spending time on it.",
    status: "Pending Approval",
    contact: "calm@email.com",
    location: ["San Francisco"],
    revenue: "75M",
    funding: "115M",
    size: "51-200",
  },
  {
    id: "5",
    name: "Capella Space",
    img_url:
      "https://photos.angel.co/startups/i/2915795-1e842423395200c8a431deb7d1ee0817-medium_jpg.jpg?buster=1561485850",
    info: "Capella Space is a data company that provides persistent and reliable information from space with it's constellation of (very small) satellites. Capella's satellites can see through the clouds and at night time making them immune to bad weather or light conditions. We deliver information that informs a wide range of global decisions to save money, time, and lives. We monitor changes constantly with no interruptions. Some call it reliability, we call it persistence information collection.",
    status: "Researching",
    contact: "capella@email.com",
    location: ["San Francisco"],
    revenue: "35.7M",
    size: "51-200",
  },
  {
    id: "6",
    name: "Checkr",
    img_url:
      "https://photos.angel.co/startups/i/395014-2a2164ef6a8cd5954eb970228e62ce15-medium_jpg.jpg?buster=1589645742",
    info: "Checkr provides modern and compliant background checks for global enterprises and startups. Since graduating Y-Combinator in 2014, Checkr’s product has shifted the on-demand economy. More than 3,000 businesses trust Checkr for their background screenings including Uber, Instacart, Handy, Zenefits, GrubHub, Caviar, and more. Checkr is featured on Business Insider as one of the top startups to watch in 2016.",
    status: "Researching",
    contact: "checkr@email.com",
    location: ["San Francisco"],
    revenue: "71.6M",
    funding: "149M",
    size: "201-500",
  },
];
